name: prommis
channels:
  - conda-forge
  - nodefaults
dependencies:
  - python=3.12
  - pip
  - pyyaml
  - reaktoro=2.13.0
  - cyipopt=1.7.0
  - pip:
    - "prommis[ui,dev,watertap]"
    - idaes-examples
    # - git+https://github.com/IDAES/examples.git@2.8_rel
    # - git+https://github.com/IDAES/prommis.git@scaling_toolbox
